import matplotlib.pyplot as plt
import numpy as np

t, pi, k, c = np.genfromtxt('data/had_E_1e6_no_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, c, 'b', label=r'$c$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_h / dE_h$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_h = 10^6$ GeV (no cooling factor)')
plt.legend()
plt.savefig('build/had_E_1e6_no_cf.png')
plt.close()

t, pi, k, c = np.genfromtxt('data/had_E_1e9_no_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, c, 'b', label=r'$c$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_h / dE_h$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_h = 10^9$ GeV (no cooling factor)')
plt.legend()
plt.savefig('build/had_E_1e9_no_cf.png')
plt.close()

t, pi, k, c = np.genfromtxt('data/had_E_1e6_with_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, c, 'b', label=r'$c$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_h / dE_h$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_h = 10^6$ GeV (with cooling factor)')
plt.legend()
plt.savefig('build/had_E_1e6_with_cf.png')
plt.close()

t, pi, k, c = np.genfromtxt('data/had_E_1e9_with_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, c, 'b', label=r'$c$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_h / dE_h$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_h = 10^9$ GeV (with cooling factor)')
plt.legend()
plt.savefig('build/had_E_1e9_with_cf.png')
plt.close()

t, pi, k, d0 = np.genfromtxt('data/neu_E_1e6_no_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, d0, 'b', label=r'$D_0$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_\nu / dE_\nu$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_\nu = 10^6$ GeV (no cooling factor)')
plt.legend()
plt.savefig('build/neu_E_1e6_no_cf.png')
plt.close()

t, pi, k, d0 = np.genfromtxt('data/neu_E_1e9_no_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, d0, 'b', label=r'$D_0$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_\nu / dE_\nu$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_\nu = 10^9$ GeV (no cooling factor)')
plt.legend()
plt.savefig('build/neu_E_1e9_no_cf.png')
plt.close()

t, pi, k, d0 = np.genfromtxt('data/neu_E_1e6_with_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, d0, 'b', label=r'$D_0$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_\nu / dE_\nu$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_\nu = 10^6$ GeV (with cooling factor)')
plt.legend()
plt.savefig('build/neu_E_1e6_with_cf.png')
plt.close()

t, pi, k, d0 = np.genfromtxt('data/neu_E_1e9_with_cf.txt', unpack=True)
plt.plot(t, pi, 'r', label=r'$\pi$')
plt.plot(t, k, 'k', label=r'$K$')
plt.plot(t, d0, 'b', label=r'$D_0$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$t$ / s')
plt.ylabel(r'$dN_\nu / dE_\nu$ / GeV$^{-1}$s$^{-1}$')
plt.title(r'$E_\nu = 10^9$ GeV (with cooling factor)')
plt.legend()
plt.savefig('build/neu_E_1e9_with_cf.png')
plt.close()

E, pi, k, d0 = np.genfromtxt('data/neu_with_cf.txt', unpack=True)
plt.plot(E, pi, 'r', label=r'$\pi$')
plt.plot(E, k, 'k', label=r'$K$')
plt.plot(E, d0, 'b', label=r'$D_0$')
plt.xscale('log')
plt.yscale('log')
plt.xlabel(r'$E$ / GeV')
plt.ylabel(r'$dN_\nu / dE_\nu$ / GeV$^{-1}$')
plt.title(r'(with cooling factor)')
plt.legend()
plt.savefig('build/neu_with_cf.png')
plt.close()
